name: pdf_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  pdfx: ^2.8.0
  path: ^1.9.0
  open_file: ^3.5.10
  image: ^4.5.2


dev_dependencies:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


